// Portfolio Mock Data - All static content for the portfolio

export const PERSONAL_INFO = {
  name: "Alex Chen",
  title: "Senior Frontend Engineer",
  tagline: "Building exceptional digital experiences",
  description: "I'm a passionate frontend engineer with 8+ years of experience crafting scalable, performant web applications. I specialize in React ecosystems, design systems, and turning complex problems into elegant solutions.",
  location: "San Francisco, CA",
  email: "alex@example.dev",
  resumeUrl: "/resume.pdf",
  availability: "Open to opportunities",
};

export const SOCIAL_LINKS = [
  { name: "GitHub", url: "https://github.com", icon: "Github" },
  { name: "LinkedIn", url: "https://linkedin.com", icon: "Linkedin" },
  { name: "Twitter", url: "https://twitter.com", icon: "Twitter" },
  { name: "Email", url: "mailto:alex@example.dev", icon: "Mail" },
];

export const SKILLS = [
  {
    category: "Frontend",
    items: [
      { name: "React", level: 95 },
      { name: "TypeScript", level: 90 },
      { name: "Next.js", level: 88 },
      { name: "Vue.js", level: 75 },
      { name: "Tailwind CSS", level: 92 },
    ],
  },
  {
    category: "Tools & Platforms",
    items: [
      { name: "Git", level: 90 },
      { name: "Figma", level: 85 },
      { name: "AWS", level: 70 },
      { name: "Docker", level: 72 },
      { name: "CI/CD", level: 80 },
    ],
  },
  {
    category: "Specializations",
    items: [
      { name: "Design Systems", level: 93 },
      { name: "Performance", level: 88 },
      { name: "Accessibility", level: 85 },
      { name: "Testing", level: 82 },
      { name: "Animation", level: 78 },
    ],
  },
];

export const TECH_STACK = [
  { name: "React", icon: "⚛️" },
  { name: "TypeScript", icon: "📘" },
  { name: "Next.js", icon: "▲" },
  { name: "Tailwind", icon: "🎨" },
  { name: "Node.js", icon: "💚" },
  { name: "GraphQL", icon: "◈" },
  { name: "PostgreSQL", icon: "🐘" },
  { name: "Redis", icon: "🔴" },
  { name: "Docker", icon: "🐳" },
  { name: "AWS", icon: "☁️" },
  { name: "Figma", icon: "🎭" },
  { name: "Vercel", icon: "▲" },
];

export const EXPERIENCES = [
  {
    id: 1,
    role: "Senior Frontend Engineer",
    company: "TechCorp Inc.",
    companyUrl: "https://example.com",
    location: "San Francisco, CA",
    period: "2022 - Present",
    type: "Full-time",
    description: "Leading frontend architecture for a B2B SaaS platform serving 500K+ users. Spearheading design system development and performance optimization initiatives.",
    achievements: [
      "Led migration from legacy codebase to React 18, improving load times by 40%",
      "Built and maintained component library used across 5 product teams",
      "Mentored 4 junior developers, establishing frontend best practices",
      "Reduced bundle size by 35% through code splitting and lazy loading",
    ],
    technologies: ["React", "TypeScript", "GraphQL", "Tailwind CSS", "Storybook"],
  },
  {
    id: 2,
    role: "Frontend Engineer",
    company: "StartupXYZ",
    companyUrl: "https://example.com",
    location: "Remote",
    period: "2020 - 2022",
    type: "Full-time",
    description: "Core member of a fast-paced fintech startup, building user-facing applications from 0 to 1 with focus on security and UX.",
    achievements: [
      "Architected real-time trading dashboard handling 10K+ concurrent users",
      "Implemented OAuth 2.0 and 2FA, achieving SOC 2 compliance",
      "Developed mobile-first responsive design system",
      "Collaborated with design team to improve conversion by 25%",
    ],
    technologies: ["React", "Redux", "WebSockets", "D3.js", "Jest"],
  },
  {
    id: 3,
    role: "Frontend Developer",
    company: "Digital Agency Co.",
    companyUrl: "https://example.com",
    location: "New York, NY",
    period: "2018 - 2020",
    type: "Full-time",
    description: "Delivered pixel-perfect web experiences for Fortune 500 clients across e-commerce, healthcare, and media industries.",
    achievements: [
      "Built 15+ client websites with 99% satisfaction rate",
      "Created reusable component templates reducing project time by 30%",
      "Led accessibility audits achieving WCAG 2.1 AA compliance",
      "Optimized Core Web Vitals across client portfolio",
    ],
    technologies: ["React", "Vue.js", "Sass", "WordPress", "Shopify"],
  },
  {
    id: 4,
    role: "Junior Web Developer",
    company: "Tech Solutions Ltd.",
    companyUrl: "https://example.com",
    location: "Boston, MA",
    period: "2016 - 2018",
    type: "Full-time",
    description: "Started career building responsive websites and learning modern frontend frameworks in a supportive team environment.",
    achievements: [
      "Developed and maintained 20+ WordPress sites",
      "Learned React and Vue.js, transitioning team to modern stack",
      "Built custom WordPress themes and plugins",
      "Improved site performance scores by average of 20 points",
    ],
    technologies: ["JavaScript", "jQuery", "PHP", "WordPress", "CSS3"],
  },
];

export const PROJECTS = [
  {
    id: "design-system",
    title: "Enterprise Design System",
    subtitle: "Component Library",
    description: "A comprehensive design system built with React, TypeScript, and Tailwind CSS. Features 50+ accessible components with full documentation and Storybook integration.",
    longDescription: "Led the development of a scalable design system that unified the visual language across 5 product teams. The system includes a token-based theming engine, accessibility-first components, and extensive documentation that reduced onboarding time for new developers by 60%.",
    image: "/placeholder.svg",
    technologies: ["React", "TypeScript", "Tailwind CSS", "Storybook", "Radix UI"],
    features: [
      "50+ fully accessible components",
      "Dark/light theme support",
      "Comprehensive documentation",
      "Figma integration",
      "Tree-shakable exports",
    ],
    metrics: {
      adoption: "5 teams",
      components: "50+",
      satisfaction: "98%",
    },
    liveUrl: "https://example.com",
    githubUrl: "https://github.com",
    featured: true,
    category: "Design System",
  },
  {
    id: "analytics-dashboard",
    title: "Real-time Analytics Dashboard",
    subtitle: "Data Visualization",
    description: "High-performance dashboard visualizing real-time data streams with WebSocket connections and interactive D3.js charts.",
    longDescription: "Built a real-time analytics platform capable of handling 10,000+ concurrent connections. Implemented efficient data streaming with WebSockets, created custom D3.js visualizations, and optimized rendering for smooth 60fps animations even with large datasets.",
    image: "/placeholder.svg",
    technologies: ["React", "D3.js", "WebSockets", "Redis", "Node.js"],
    features: [
      "Real-time data streaming",
      "Custom chart components",
      "Export to PDF/CSV",
      "Collaborative features",
      "Mobile-responsive",
    ],
    metrics: {
      users: "10K+",
      uptime: "99.9%",
      latency: "<50ms",
    },
    liveUrl: "https://example.com",
    githubUrl: "https://github.com",
    featured: true,
    category: "Web App",
  },
  {
    id: "ecommerce-platform",
    title: "Headless E-commerce Platform",
    subtitle: "Full-Stack Commerce",
    description: "Modern e-commerce solution with headless CMS, optimized checkout flow, and seamless payment integrations.",
    longDescription: "Architected a headless e-commerce platform that achieved 98/100 Lighthouse performance score. Implemented optimistic UI updates, smart caching strategies, and a streamlined checkout that improved conversion rates by 35%.",
    image: "/placeholder.svg",
    technologies: ["Next.js", "Shopify API", "Stripe", "Sanity CMS", "Vercel"],
    features: [
      "Headless architecture",
      "Optimized checkout",
      "Inventory management",
      "Multi-currency support",
      "SEO optimized",
    ],
    metrics: {
      performance: "98/100",
      conversion: "+35%",
      loadTime: "1.2s",
    },
    liveUrl: "https://example.com",
    githubUrl: "https://github.com",
    featured: true,
    category: "E-commerce",
  },
  {
    id: "developer-tools",
    title: "Developer Productivity Suite",
    subtitle: "Chrome Extension",
    description: "Browser extension suite for developers featuring API testing, color picking, and responsive design testing tools.",
    longDescription: "Created a comprehensive developer toolkit as a Chrome extension. Features include an API request builder, color palette extractor, responsive viewport tester, and performance profiler. Downloaded by 15,000+ developers worldwide.",
    image: "/placeholder.svg",
    technologies: ["JavaScript", "Chrome APIs", "React", "IndexedDB", "Webpack"],
    features: [
      "API request builder",
      "Color palette tools",
      "Responsive tester",
      "Performance profiler",
      "Local data storage",
    ],
    metrics: {
      downloads: "15K+",
      rating: "4.8/5",
      reviews: "500+",
    },
    liveUrl: "https://example.com",
    githubUrl: "https://github.com",
    featured: false,
    category: "Developer Tool",
  },
  {
    id: "ai-writing-assistant",
    title: "AI Writing Assistant",
    subtitle: "SaaS Application",
    description: "AI-powered writing tool with grammar checking, style suggestions, and content generation capabilities.",
    longDescription: "Developed the frontend for an AI writing assistant that processes text in real-time. Implemented streaming responses for instant feedback, collaborative editing features, and an intuitive UI that makes AI tools accessible to non-technical users.",
    image: "/placeholder.svg",
    technologies: ["React", "OpenAI API", "Tiptap Editor", "Supabase", "Tailwind"],
    features: [
      "Real-time AI suggestions",
      "Rich text editor",
      "Template library",
      "Team collaboration",
      "Export options",
    ],
    metrics: {
      users: "5K+",
      accuracy: "95%",
      timesSaved: "40%",
    },
    liveUrl: "https://example.com",
    githubUrl: "https://github.com",
    featured: false,
    category: "SaaS",
  },
  {
    id: "portfolio-template",
    title: "Open Source Portfolio",
    subtitle: "Template",
    description: "Modern, customizable portfolio template for developers. Features smooth animations and dark mode support.",
    longDescription: "Created this very portfolio as an open-source template. Built with modern React patterns, Framer Motion animations, and a fully customizable design system. Downloaded and used by 500+ developers globally.",
    image: "/placeholder.svg",
    technologies: ["React", "Framer Motion", "Tailwind CSS", "Vite"],
    features: [
      "Fully customizable",
      "Smooth animations",
      "Dark/light mode",
      "SEO optimized",
      "Responsive design",
    ],
    metrics: {
      stars: "1.2K",
      forks: "300+",
      contributors: "25",
    },
    liveUrl: "https://example.com",
    githubUrl: "https://github.com",
    featured: false,
    category: "Open Source",
  },
];

export const NAV_LINKS = [
  { name: "Home", href: "/" },
  { name: "About", href: "#about" },
  { name: "Experience", href: "#experience" },
  { name: "Projects", href: "#projects" },
  { name: "Contact", href: "#contact" },
];

export const STATS = [
  { label: "Years Experience", value: "8+" },
  { label: "Projects Delivered", value: "50+" },
  { label: "Happy Clients", value: "30+" },
  { label: "Open Source Stars", value: "2K+" },
];
